<a href="https://colab.research.google.com/github/imdvamshi/AIML/blob/main/Projects/pandasproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [196]:
import pandas as pd
import numpy as np

# **loading the data**

In [197]:
data = pd.read_csv("students_performance.csv")
data.head()

,Student_ID,Name,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Final_Result
0,101,Aarav,Male,78.0,82.0,75,88,3,Yes,Pass
1,102,Diya,Female,92.0,95.0,91,96,5,No,Pass
2,103,Rahul,Male,67.0,72.0,70,80,2,Yes,Pass
3,104,Sneha,Female,85.0,88.0,84,90,4,No,Pass
4,105,Vikram,Male,45.0,50.0,48,60,1,Yes,Fail

# **understand the data**

In [198]:
print(data.shape)

(60, 10)

In [199]:
print(data.dtypes)

Student_ID        int64
Name             object
Gender           object
Maths           float64
Science         float64
English           int64
Attendance        int64
Study_Hours       int64
Sports           object
Final_Result     object
dtype: object

# **Data Cleaning**

In [200]:
print(data.isnull().sum())

Student_ID      0
Name            0
Gender          0
Maths           1
Science         1
English         0
Attendance      0
Study_Hours     0
Sports          0
Final_Result    0
dtype: int64

In [201]:
data=data.dropna()

In [202]:
data

,Student_ID,Name,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Final_Result
0,101,Aarav,Male,78.0,82.0,75,88,3,Yes,Pass
1,102,Diya,Female,92.0,95.0,91,96,5,No,Pass
2,103,Rahul,Male,67.0,72.0,70,80,2,Yes,Pass
3,104,Sneha,Female,85.0,88.0,84,90,4,No,Pass
4,105,Vikram,Male,45.0,50.0,48,60,1,Yes,Fail
5,106,Ananya,Female,96.0,98.0,97,99,6,No,Pass
6,107,Karan,Male,73.0,70.0,68,75,2,Yes,Pass
7,108,Priya,Female,88.0,85.0,90,92,4,No,Pass
8,109,Rohit,Male,55.0,58.0,60,65,1,Yes,Fail
9,110,Meera,Female,91.0,89.0,94,95,5,No,Pass
10,111,Arjun,Male,64.0,66.0,63,70,2,Yes,Pass
11,112,Kavya,Female,79.0,81.0,80,85,3,No,Pass
12,113,Manoj,Male,34.0,40.0,38,50,1,Yes,Fail
13,114,Isha,Female,87.0,90.0,86,91,4,No,Pass
14,115,Varun,Male,72.0,74.0,71,78,2,Yes,Pass
15,116,Ritika,Female,95.0,97.0,96,98,6,No,Pass
16,117,Aditya,Male,61.0,65.0,60,68,2,Yes,Pass
17,118,Pooja,Female,83.0,84.0,82,89,3,No,Pass
18,119,Nikhil,Male,49.0,52.0,50,58,1,Yes,Fail
19,120,Neha,Female,90.0,92.0,91,94,5,No,Pass
20,121,Harsha,Male,76.0,79.0,74,82,3,Yes,Pass
21,122,Aditi,Female,89.0,91.0,88,93,4,No,Pass
22,123,Ramesh,Male,58.0,60.0,57,64,1,Yes,Fail
23,124,Sanjana,Female,93.0,95.0,94,97,5,No,Pass
24,125,Tejas,Male,69.0,71.0,68,74,2,Yes,Pass
25,126,Lavanya,Female,84.0,86.0,85,90,4,No,Pass
26,127,Surya,Male,41.0,45.0,43,55,1,Yes,Fail
27,128,Keerthi,Female,97.0,99.0,98,100,6,No,Pass
28,129,Mahesh,Male,74.0,76.0,72,80,3,Yes,Pass
29,130,Divya,Female,88.0,87.0,89,92,4,No,Pass
30,131,Akhil,Male,53.0,55.0,54,62,1,Yes,Fail
31,132,Nandini,Female,91.0,93.0,92,95,5,No,Pass
32,133,Sai,Male,66.0,68.0,65,72,2,Yes,Pass
33,134,Anusha,Female,82.0,85.0,83,88,3,No,Pass
34,135,Ravi,Male,39.0,42.0,40,52,1,Yes,Fail
35,136,Shreya,Female,94.0,96.0,95,98,6,No,Pass
36,137,Krishna,Male,71.0,73.0,70,77,2,Yes,Pass
37,138,Bhavana,Female,86.0,88.0,87,91,4,No,Pass
38,139,Naresh,Male,47.0,49.0,46,57,1,Yes,Fail
39,140,Madhavi,Female,90.0,91.0,89,94,5,No,Pass
40,141,Chaitu,Male,77.0,78.0,76,83,3,Yes,Pass
41,142,Deepika,Female,85.0,87.0,86,90,4,No,Pass
42,143,Gopi,Male,62.0,64.0,61,69,2,Yes,Pass
43,144,Harini,Female,92.0,94.0,93,96,5,No,Pass
44,145,Praneeth,Male,56.0,59.0,57,63,1,Yes,Fail
45,146,Sushma,Female,89.0,90.0,91,93,4,No,Pass
46,147,Venu,Male,68.0,70.0,67,73,2,Yes,Pass
47,148,Akshaya,Female,96.0,97.0,98,99,6,No,Pass
48,149,Rajesh,Male,44.0,46.0,45,54,1,Yes,Fail
49,150,Swathi,Female,87.0,89.0,88,92,4,No,Pass
50,151,Tarun,Male,75.0,77.0,74,81,3,Yes,Pass
51,152,Navya,Female,93.0,94.0,95,97,5,No,Pass
52,153,Kishore,Male,59.0,61.0,60,66,2,Yes,Pass
53,154,Sindhu,Female,84.0,85.0,86,89,4,No,Pass
54,155,Ajay,Male,36.0,38.0,35,48,1,Yes,Fail
55,156,Monika,Female,91.0,92.0,93,95,5,No,Pass
56,157,Uday,Male,70.0,72.0,71,76,2,Yes,Pass
57,158,Tejal,Female,88.0,90.0,89,93,4,No,Pass

In [203]:
print(data.isnull().sum())

Student_ID      0
Name            0
Gender          0
Maths           0
Science         0
English         0
Attendance      0
Study_Hours     0
Sports          0
Final_Result    0
dtype: int64

In [204]:
print(data.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
dtype: bool

# **Explorative Data Analysis**

In [205]:
# student who scored highest and least
data['total'] = data['Maths'] + data['Science'] + data['English']
data.head()

,Student_ID,Name,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Final_Result,total
0,101,Aarav,Male,78.0,82.0,75,88,3,Yes,Pass,235.0
1,102,Diya,Female,92.0,95.0,91,96,5,No,Pass,278.0
2,103,Rahul,Male,67.0,72.0,70,80,2,Yes,Pass,209.0
3,104,Sneha,Female,85.0,88.0,84,90,4,No,Pass,257.0
4,105,Vikram,Male,45.0,50.0,48,60,1,Yes,Fail,143.0

In [206]:
# highest
data[data['total'] == data['total'].max()]

,Student_ID,Name,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Final_Result,total
27,128,Keerthi,Female,97.0,99.0,98,100,6,No,Pass,294.0

In [207]:
# least
data[data['total'] == data['total'].min()]

,Student_ID,Name,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Final_Result,total
54,155,Ajay,Male,36.0,38.0,35,48,1,Yes,Fail,109.0

In [208]:
# average marks and subject wise avg
data['average'] = (data['Maths'] + data['Science'] + data['English'])/3
data.head()

,Student_ID,Name,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Final_Result,total,average
0,101,Aarav,Male,78.0,82.0,75,88,3,Yes,Pass,235.0,78.333333
1,102,Diya,Female,92.0,95.0,91,96,5,No,Pass,278.0,92.666667
2,103,Rahul,Male,67.0,72.0,70,80,2,Yes,Pass,209.0,69.666667
3,104,Sneha,Female,85.0,88.0,84,90,4,No,Pass,257.0,85.666667
4,105,Vikram,Male,45.0,50.0,48,60,1,Yes,Fail,143.0,47.666667

In [209]:
# Maths Average
print(data['Maths'].sum(axis=0))

4324.0

In [210]:
# Science Average
print(data['Science'].sum(axis=0))

4440.0

In [211]:
# English Average
print(data['English'].sum(axis=0))

4348

In [212]:
# relationship between studyhrs and marks
print(data['Study_Hours'].corr(data['total']))

0.9359377102848376

In [213]:
# relationship betweem studyhrs and pass/fail
data['Final_Result']=data['Final_Result'].map({'Pass':1,'Fail':0})
data.head()

,Student_ID,Name,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Final_Result,total,average
0,101,Aarav,Male,78.0,82.0,75,88,3,Yes,1,235.0,78.333333
1,102,Diya,Female,92.0,95.0,91,96,5,No,1,278.0,92.666667
2,103,Rahul,Male,67.0,72.0,70,80,2,Yes,1,209.0,69.666667
3,104,Sneha,Female,85.0,88.0,84,90,4,No,1,257.0,85.666667
4,105,Vikram,Male,45.0,50.0,48,60,1,Yes,0,143.0,47.666667

In [214]:
print(data['Study_Hours'].corr(data['Final_Result']))

0.6808527306727367

In [215]:
# Sports students performing better?
data.groupby('Sports')['total'].mean()

Sports
No     269.758621
Yes    182.379310
Name: total, dtype: float64

In [216]:
# attendance affecting results
print(data['Attendance'].corr(data['Final_Result']))

0.8041486776291861

# **Statistical Analysis**

In [217]:
math_marks = np.array(data['Maths'])
science_marks = np.array(data['Science'])
english_marks = np.array(data['English'])
study_hrs = np.array(data['Study_Hours'])

In [218]:
print("Average of math marks:",math_marks.mean())
print("Average of science marks:",science_marks.mean())
print("Average of english marks:",english_marks.mean())
print("Average Study Hours:",study_hrs.mean())

Average of math marks: 74.55172413793103
Average of science marks: 76.55172413793103
Average of english marks: 74.96551724137932
Average Study Hours: 3.1551724137931036

# **Save cleaned data back into csv**

In [219]:
data.head()

,Student_ID,Name,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Final_Result,total,average
0,101,Aarav,Male,78.0,82.0,75,88,3,Yes,1,235.0,78.333333
1,102,Diya,Female,92.0,95.0,91,96,5,No,1,278.0,92.666667
2,103,Rahul,Male,67.0,72.0,70,80,2,Yes,1,209.0,69.666667
3,104,Sneha,Female,85.0,88.0,84,90,4,No,1,257.0,85.666667
4,105,Vikram,Male,45.0,50.0,48,60,1,Yes,0,143.0,47.666667

In [220]:
data.to_csv("cleaned_students_performance.csv",index=False)