## **Topic 1: Ensemble Learning ⭐**

### Ensemble Learning is the technique of combining multiple models to produce a better prediction than a single model. Types of EL :
### 1. Bagging ( Bootstrap Aggregating ) - Train many models independently and combine results. Ex : Random Forest

### 2. Boosting - Train models sequentially.Each new model focuses on previous mistakes. Ex : AdaBoost, Gradient Boosting, XGBoost, LightGBM, CatBoost

### 3. Voting - Train different models like Logistic Regression, KNN, Decision Tree -> Majority Vote

### 4. Stacking - Train multiple models -> Use their predictions -> Train another model on those predictions

In [1]:
import numpy as np

In [2]:
# Data for Regression
x = np.array([[1],[2],[3],[4],[5]])
y = np.array([10,14,21,25,32])

In [3]:
# Data for Classification
a = np.array([
    [1],[2],[3],[4],[5],
    [6],[7],[8],[9],[10],
    [11],[12],[13],[14],[15],
    [16],[17],[18],[19],[20]
])
b = np.array([
    0,0,0,0,0,
    0,0,0,1,1,
    1,1,1,1,1,
    1,1,1,1,1
])

## **Bagging**

In [4]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
model = BaggingClassifier(estimator=DecisionTreeClassifier(),n_estimators=100)
model.fit(a,b)
prediction = model.predict([[24]])
print(prediction)

[1]

In [5]:
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
model = BaggingRegressor(estimator=DecisionTreeRegressor(),n_estimators=100)
model.fit(x,y)
prediction = model.predict([[12]])
print(prediction)

[28.74]

### Bagging is the concept/technique.

### Random Forest is one implementation of that concept ( algorithm ).

## **Boosting**

### AdaBoost

In [6]:
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier(n_estimators=100)
model.fit(a,b)
prediction = model.predict([[25]])
print(prediction)

[1]

In [7]:
from sklearn.ensemble import AdaBoostRegressor
model = AdaBoostRegressor(n_estimators=100)
model.fit(x,y)
prediction = model.predict([[14]])
print(prediction)

[32.]

### Gradient Boosting
### AdaBoost : Focuses on wrongly predicted samples. Which rows are wrong?

### Gradient Boosting : Focuses on residual errors. By how much is it wrong? (Actual - Predicted).

In [8]:
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier(n_estimators=85)
model.fit(a,b)
prediction = model.predict([[25]])
print(prediction)

[1]

In [9]:
from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor(n_estimators=85)
model.fit(x,y)
prediction = model.predict([[13]])
print(prediction)

[31.99850352]

### XGBoost : Extreme Gradient Boosting - optimized and improved version of Gradient Boosting.

### Gradient Boosting had issues : Slow Training, Overfitting, High Memory Usage

### XGBoost improves these.

In [10]:
# pip install xgboost
from xgboost import XGBClassifier
model = XGBClassifier(n_estimators=100)
model.fit(a,b)
prediction = model.predict([[25]])
print(prediction)

[1]

In [11]:
from xgboost import XGBRegressor
model = XGBRegressor()
model.fit(x,y)
prediction = model.predict([[13]])
print(prediction)

[31.998966]

### LightGBM - A fast implementation of Gradient Boosting.

In [12]:
# pip install lightgbm
from lightgbm import LGBMClassifier
model = LGBMClassifier(n_estimators=100)
model.fit(a,b)
prediction = model.predict([[25]])
print(prediction)

[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.
[LightGBM] [Info] Number of positive: 12, number of negative: 8
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data points in the train set: 20, number of used features: 0
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.600000 -> initscore=0.405465
[LightGBM] [Info] Start training from score 0.405465
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[1]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [13]:
from lightgbm import LGBMRegressor
model = LGBMRegressor()
model.fit(x,y)
prediction = model.predict([[13]])
print(prediction)

[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data points in the train set: 5, number of used features: 0
[LightGBM] [Info] Start training from score 20.400000
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[20.4]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

### CatBoost - Best for Categorical Data

In [14]:
import sys
!{sys.executable} -m pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)

In [15]:
import pandas as pd
m = pd.DataFrame({
    'Gender':['Male','Female','Male','Female','Male'],
    'City':['Hyd','Delhi','Hyd','Mumbai','Delhi'],
    'Age':[22,25,30,28,35]
})
n = [1,0,1,0,1]
from catboost import CatBoostClassifier #CatBoostRegressor also there
model = CatBoostClassifier(iterations=100) # iterations same as n_estimators
model.fit(m,n,cat_features=['Gender','City'])
prediction = model.predict([['Male','Hyd',23]])
print(prediction)

Learning rate set to 0.008859
0:	learn: 0.6922325	total: 48.7ms	remaining: 4.82s
1:	learn: 0.6906675	total: 48.9ms	remaining: 2.39s
2:	learn: 0.6891074	total: 49ms	remaining: 1.58s
3:	learn: 0.6875524	total: 49.2ms	remaining: 1.18s
4:	learn: 0.6871484	total: 49.3ms	remaining: 938ms
5:	learn: 0.6855996	total: 49.5ms	remaining: 775ms
6:	learn: 0.6840558	total: 49.6ms	remaining: 659ms
7:	learn: 0.6839551	total: 49.6ms	remaining: 571ms
8:	learn: 0.6833434	total: 49.7ms	remaining: 503ms
9:	learn: 0.6824479	total: 49.9ms	remaining: 449ms
10:	learn: 0.6809144	total: 50ms	remaining: 404ms
11:	learn: 0.6793859	total: 50.1ms	remaining: 367ms
12:	learn: 0.6778623	total: 50.2ms	remaining: 336ms
13:	learn: 0.6774671	total: 50.3ms	remaining: 309ms
14:	learn: 0.6773692	total: 50.4ms	remaining: 286ms
15:	learn: 0.6764843	total: 50.5ms	remaining: 265ms
16:	learn: 0.6749702	total: 50.6ms	remaining: 247ms
17:	learn: 0.6734610	total: 50.7ms	remaining: 231ms
18:	learn: 0.6723579	total: 50.8ms	remaining: 217ms
19:	learn: 0.6708568	total: 50.9ms	remaining: 204ms
20:	learn: 0.6693606	total: 51ms	remaining: 192ms
21:	learn: 0.6678691	total: 51.2ms	remaining: 181ms
22:	learn: 0.6670031	total: 51.3ms	remaining: 172ms
23:	learn: 0.6661377	total: 51.4ms	remaining: 163ms
24:	learn: 0.6646565	total: 51.5ms	remaining: 155ms
25:	learn: 0.6631801	total: 51.6ms	remaining: 147ms
26:	learn: 0.6617084	total: 51.7ms	remaining: 140ms
27:	learn: 0.6602414	total: 51.8ms	remaining: 133ms
28:	learn: 0.6596049	total: 51.9ms	remaining: 127ms
29:	learn: 0.6595136	total: 52ms	remaining: 121ms
30:	learn: 0.6594228	total: 52.1ms	remaining: 116ms
31:	learn: 0.6579635	total: 52.2ms	remaining: 111ms
32:	learn: 0.6573712	total: 52.3ms	remaining: 106ms
33:	learn: 0.6565254	total: 52.4ms	remaining: 102ms
34:	learn: 0.6554608	total: 52.5ms	remaining: 97.6ms
35:	learn: 0.6543987	total: 52.7ms	remaining: 93.7ms
36:	learn: 0.6529551	total: 52.8ms	remaining: 89.9ms
37:	learn: 0.6528667	total: 52.9ms	remaining: 86.3ms
38:	learn: 0.6514282	total: 53ms	remaining: 82.8ms
39:	learn: 0.6499944	total: 53.1ms	remaining: 79.6ms
40:	learn: 0.6485650	total: 53.2ms	remaining: 76.5ms
41:	learn: 0.6471402	total: 53.2ms	remaining: 73.5ms
42:	learn: 0.6463123	total: 53.4ms	remaining: 70.8ms
43:	learn: 0.6448947	total: 53.5ms	remaining: 68.1ms
44:	learn: 0.6434815	total: 53.6ms	remaining: 65.5ms
45:	learn: 0.6420729	total: 53.7ms	remaining: 63ms
46:	learn: 0.6412545	total: 53.8ms	remaining: 60.6ms
47:	learn: 0.6398529	total: 53.8ms	remaining: 58.3ms
48:	learn: 0.6384557	total: 53.9ms	remaining: 56.1ms
49:	learn: 0.6370630	total: 54ms	remaining: 54ms
50:	learn: 0.6369804	total: 54.1ms	remaining: 52ms
51:	learn: 0.6361731	total: 54.3ms	remaining: 50.1ms
52:	learn: 0.6347878	total: 54.3ms	remaining: 48.2ms
53:	learn: 0.6334068	total: 54.4ms	remaining: 46.4ms
54:	learn: 0.6320303	total: 54.5ms	remaining: 44.6ms
55:	learn: 0.6312206	total: 54.7ms	remaining: 43ms
56:	learn: 0.6298507	total: 54.8ms	remaining: 41.3ms
57:	learn: 0.6284852	total: 54.8ms	remaining: 39.7ms
58:	learn: 0.6271239	total: 54.9ms	remaining: 38.2ms
59:	learn: 0.6257670	total: 55ms	remaining: 36.7ms
60:	learn: 0.6256882	total: 55.1ms	remaining: 35.2ms
61:	learn: 0.6243360	total: 55.2ms	remaining: 33.8ms
62:	learn: 0.6229880	total: 55.3ms	remaining: 32.5ms
63:	learn: 0.6229106	total: 55.4ms	remaining: 31.1ms
64:	learn: 0.6219214	total: 55.5ms	remaining: 29.9ms
65:	learn: 0.6205811	total: 55.6ms	remaining: 28.6ms
66:	learn: 0.6194521	total: 55.7ms	remaining: 27.4ms
67:	learn: 0.6181197	total: 55.8ms	remaining: 26.3ms
68:	learn: 0.6167914	total: 55.9ms	remaining: 25.1ms
69:	learn: 0.6160204	total: 56ms	remaining: 24ms
70:	learn: 0.6149043	total: 56.1ms	remaining: 22.9ms
71:	learn: 0.6143680	total: 56.3ms	remaining: 21.9ms
72:	learn: 0.6136018	total: 56.4ms	remaining: 20.9ms
73:	learn: 0.6122879	total: 56.5ms	remaining: 19.9ms
74:	learn: 0.6118204	total: 56.6ms	remaining: 18.9ms
75:	learn: 0.6105123	total: 56.7ms	remaining: 17.9ms
76:	learn: 0.6100481	total: 56.8ms	remaining: 17ms
77:	learn: 0.6092903	total: 56.9ms	remaining: 16.1ms
78:	learn: 0.6079904	total: 57ms	remaining: 15.2ms
79:	learn: 0.6066945	total: 57.1ms	remaining: 14.3ms
80:	learn: 0.6057412	total: 57.2ms	remaining: 13.4ms
81:	learn: 0.6051783	total: 57.4ms	remaining: 12.6ms
82:	learn: 0.6042285	total: 57.5ms	remaining: 11.8ms
83:	learn: 0.6037185	total: 57.6ms	remaining: 11ms
84:	learn: 0.6036483	total: 57.6ms	remaining: 10.2ms
85:	learn: 0.6023658	total: 57.7ms	remaining: 9.4ms
86:	learn: 0.6018472	total: 57.8ms	remaining: 8.64ms
87:	learn: 0.6005704	total: 58ms	remaining: 7.9ms
88:	learn: 0.5992976	total: 58.1ms	remaining: 7.18ms
89:	learn: 0.5980287	total: 58.2ms	remaining: 6.46ms
90:	learn: 0.5979607	total: 58.3ms	remaining: 5.76ms
91:	learn: 0.5968956	total: 58.4ms	remaining: 5.08ms
92:	learn: 0.5956345	total: 58.5ms	remaining: 4.4ms
93:	learn: 0.5943774	total: 58.6ms	remaining: 3.74ms
94:	learn: 0.5931241	total: 58.6ms	remaining: 3.09ms
95:	learn: 0.5923988	total: 58.8ms	remaining: 2.45ms
96:	learn: 0.5916736	total: 58.9ms	remaining: 1.82ms
97:	learn: 0.5911296	total: 59.1ms	remaining: 1.21ms
98:	learn: 0.5898864	total: 59.2ms	remaining: 597us
99:	learn: 0.5889707	total: 59.3ms	remaining: 0us
[1]

## **Voting**

## Types:

### 1. VotingClassifier - Combine multiple Classification models.


### a. Hard Voting (Classification Only) - Majority Vote, Default in VotingClassifier

### Example: LR  → 1, DT  → 1, KNN → 0 : Final → 1

### b. Soft Voting (Classification Only) - Average Probabilities of pass and fail - voting='soft'

### Example: Pass = 70%, Fail = 30% : Final → Pass



---



### 2. VotingRegressor - Combine multiple regression models.

### Working: Average predictions.

### Example: 100000, 110000, 120000 -> 110000

### Note: Hard and Soft Voting exist only for VotingClassifier.

In [16]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
model = VotingClassifier(
    estimators=[('lr',LogisticRegression()),
     ('dt',DecisionTreeClassifier()),
      ('rf',RandomForestClassifier())],voting='hard')
model.fit(a,b)
prediction = model.predict([[22]])
print(prediction)

[1]

In [17]:
from sklearn.ensemble import VotingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
model = VotingRegressor(
    estimators=[('lr',LinearRegression()),
                ('dt',DecisionTreeRegressor()),
                ('rf',RandomForestRegressor())])
model.fit(x,y)
prediction = model.predict([[12]])
print(prediction)

[43.74]

## **Stacking**

In [18]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
model = StackingClassifier(estimators=[
    ('lr',LogisticRegression()),
    ('dt',DecisionTreeClassifier()),
    ('rf',RandomForestClassifier())],final_estimator=LogisticRegression())
model.fit(a,b)
prediction = model.predict([[22]])
print(prediction)

[1]

In [19]:
from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
model = StackingRegressor(estimators=[
    ('lr',LinearRegression()),
    ('dt',DecisionTreeRegressor()),
    ('rf',RandomForestRegressor())],final_estimator=LinearRegression())
model.fit(x,y)
prediction = model.predict([[6]])
print(prediction)

[37.29806892]

# **Imbalanced Learn**

In [20]:
import pandas as pd
x = pd.DataFrame({
    'Age':[20,22,25,28,30,32,35,40,45,50]
})
y = pd.Series([0,0,0,0,0,0,0,0,1,1]) #imbalanced data

In [21]:
y.value_counts()

0    8
1    2
Name: count, dtype: int64

In [22]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42,k_neighbors=1)
x_resampled,y_resampled = smote.fit_resample(x,y)

In [25]:
print(x_resampled)

    Age
0    20
1    22
2    25
3    28
4    30
5    32
6    35
7    40
8    45
9    50
10   47
11   49
12   45
13   45
14   49
15   46

In [26]:
y_resampled.value_counts()

0    8
1    8
Name: count, dtype: int64